name = "thefarmcomputer"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[assets]
directory = "./web/dist"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[triggers]
crons = ["0 8 * * SUN"]

[[durable_objects.bindings]]
name = "STARDEW_DO"
class_name = "StardewDO"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["StardewDO"]
